version: '3.8'

services:
  backend:
    build: ./backend
    container_name: plotplay-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./games:/app/games
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/plotplay
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: plotplay-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: plotplay-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: plotplay
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: plotplay-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
