game:
  id: "romance_test"
  title: "Romance Test"
  version: "1.0.0"
  author: "Dev Team"
  nsfw_level: "explicit"

  settings:
    starting_location: "apartment"
    starting_time: "evening"
    starting_day: 1

  time_system:
    slots: ["morning", "afternoon", "evening", "night"]
    auto_advance: true
    actions_per_slot: 3