metadata:
  name: "Inventory - Give Item"
  description: "Test giving items to NPCs and transferring inventory"
  game: "coffeeshop_date"
  author: "PlotPlay Team"
  tags: ["feature-inventory", "phase-1", "transfer"]

mocks:
  writer:
    intro: "You step onto the sunlit cafe patio. The aroma of fresh coffee fills the air. You spot Alex at one of the tables."
    goto_counter: "You make your way to the coffee shop counter. The pastries gleam under the display lights."
    add_latte: "You pick up a vanilla latte from the counter, its warmth seeping into your hands."
    transfer_latte: "You slide the vanilla latte across the table to Alex. Her eyes light up. \"For me? You're so sweet!\""

  checker:
    default:
      meters: {}
      flags: {}
      character_memories: {}
      safety:
        ok: true

    add_latte:
      meters: {}
      flags: {}
      character_memories: {}
      inventory:
        - op: "add"
          item: "vanilla_latte"
          count: 1
          owner: "player"
      safety:
        ok: true

    transfer_latte:
      meters:
        alex:
          comfort: 8
      flags: {}
      character_memories:
        alex: "You gave me a vanilla latte"
      inventory:
        - op: "remove"
          item: "vanilla_latte"
          count: 1
          owner: "player"
        - op: "add"
          item: "vanilla_latte"
          count: 1
          owner: "alex"
      safety:
        ok: true

steps:
  - name: "Start game at cafe patio"
    action: start
    mock_writer_key: intro
    expect:
      node: "outside_cafe"
      location: "cafe_patio"

  - name: "Move to cafe counter"
    action: goto
    location: "cafe_counter"
    mock_writer_key: goto_counter
    expect:
      location: "cafe_counter"

  - name: "Acquire vanilla latte"
    action: say
    action_text: "I pick up a vanilla latte"
    mock_writer_key: add_latte
    expect:
      inventory_contains:
        vanilla_latte: 1

  - name: "Return to patio with Alex"
    action: goto
    location: "cafe_patio"
    mock_writer_key: intro
    expect:
      location: "cafe_patio"
      present_characters: ["player", "alex"]

  - name: "Give latte to Alex"
    action: give
    item_id: "vanilla_latte"
    target_id: "alex"
    mock_writer_key: transfer_latte
    expect:
      inventory_not_contains:
        vanilla_latte: 1
