metadata:
  name: "Inventory - Use Item"
  description: "Test using consumable items and triggering their effects"
  game: "coffeeshop_date"
  author: "PlotPlay Team"
  tags: ["feature-inventory", "phase-1", "consumable"]

mocks:
  writer:
    intro: "You step onto the sunlit cafe patio. The aroma of fresh coffee fills the air. You spot Alex at one of the tables."
    goto_counter: "You make your way to the coffee shop counter. The pastries gleam under the display lights."
    add_latte: "You pick up a vanilla latte from the counter, its warmth seeping into your hands."
    use_latte: "You savor the latte, letting the warmth steady your voice. The creamy sweetness soothes your nerves."

  checker:
    default:
      meters: {}
      flags: {}
      character_memories: {}
      safety:
        ok: true

    add_latte:
      meters: {}
      flags: {}
      character_memories: {}
      inventory:
        - op: "add"
          item: "vanilla_latte"
          count: 1
          owner: "player"
      safety:
        ok: true

steps:
  - name: "Start game at cafe patio"
    action: start
    mock_writer_key: intro
    expect:
      node: "outside_cafe"
      location: "cafe_patio"
      meters:
        player.confidence: 55

  - name: "Move to cafe counter"
    action: goto
    location: "cafe_counter"
    mock_writer_key: goto_counter
    expect:
      location: "cafe_counter"

  - name: "Acquire vanilla latte"
    action: say
    action_text: "I pick up a vanilla latte"
    mock_writer_key: add_latte
    expect:
      inventory_contains:
        vanilla_latte: 1

  - name: "Use the vanilla latte"
    action: use
    item_id: "vanilla_latte"
    mock_writer_key: use_latte
    expect:
      inventory_not_contains:
        vanilla_latte: 1
      meters:
        player.confidence: 58
      narrative_contains:
        - "latte"
        - "steady"
