game:
  id: "test_game"
  title: "Test Adventure"
  version: "1.0.0"
  author: "Dev Team"
  nsfw_level: "none"
  
  settings:
    starting_location: "tavern"
    starting_time: "evening"
    starting_day: 1
    
  time_system:
    slots: ["morning", "afternoon", "evening", "night"]
    auto_advance: true
    actions_per_slot: 3
